### ISSUE TITLE
Potential typo under

### ISSUE THREAD

**Issue by AdamTowers** [learn-co-curriculum/pass-by-reference#18]
I think the first code snippet under "Opening the Gates" has a typo:
````
names = []
 
def add_to_roster(list_of_names, name)
  list_of_names << name
end
 
add_to_roster(names, "Steven")
add_to_roster(names, "Avi")
add_to_roster(names, "Joe")
names #=> ["Steven", "Avi", "Joe"]
```` 

Shouldn't that be this...?
````
list_of_names = []
 
def add_to_roster(list_of_names, name)
  list_of_names << name
end
 
add_to_roster(names, "Steven")
add_to_roster(names, "Avi")
add_to_roster(names, "Joe")
list_of_names #=> ["Steven", "Avi", "Joe"]
````

I tried it in the IRB and the second snippet worked, and the first did not.

**Comment by jackrobinrye** [comment]
This typo is still there

**Comment by maxwellbenton** [comment]
Hi @AdamTowers,

Thank you for spotting this and providing feedback. We've updated this code snippet and corrected the typo.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
